print_power_for_3pairs <- function(diff){
  diff <- as.vector(na.omit(diff))
  mean_diff <- mean(diff)
  sd_diff <- sd(diff)
  d_paired <- mean_diff / sd_diff
  n <- length(diff)
  power <- pwr.t.test(
    n = n,
    d = d_paired,
    sig.level = 0.05,
    type = "paired",
    alternative = "greater"
  )
  print(power)
}

get_CTB_diff <- function(df,varname){
  df_Pos <- get_df_Pos(df)
  df_Pos <- df_Pos[order(df_Pos$Sample),]
  df_Neg <- get_df_Neg(df)
  df_Neg <- df_Neg[order(df_Neg$Sample),]
  diff <- df_Pos[[varname]] - df_Neg[[varname]]
  return(diff)
}

get_Type_diff <- function(df,varname){
  df_Orig <- get_df_Orig(df)
  df_Orig <- df_Orig[order(df_Orig$Sample),]
  df_Rand <- get_df_Rand(df)
  df_Rand <- df_Rand[order(df_Rand$Sample),]
  diff <- df_Orig[[varname]] - df_Rand[[varname]]
  return(diff)
}

Fig1_Comp_CTB <- function(df,varname,outfile){
  sink(file=outfile)
  df_WT <- get_df_WT(df)
  print("---------------------------------")
  print("WT_P2")
  df_WT_P2 <- get_df_P2(df_WT)
  print_power_for_3pairs(get_CTB_diff(df_WT_P2,varname))
  print("---------------------------------")
  print("WT_P4")
  df_WT_P4 <- get_df_P4(df_WT)
  print_power_for_3pairs(get_CTB_diff(df_WT_P4,varname))
  print("---------------------------------")
  print("WT_P8")
  df_WT_P8 <- get_df_P8(df_WT)
  print_power_for_3pairs(get_CTB_diff(df_WT_P8,varname))
  df_B2 <- get_df_B2(df)
  print("---------------------------------")
  print("B2_P2")
  df_B2_P2 <- get_df_P2(df_B2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P2,varname))
  print("---------------------------------")
  print("B2_P4")
  df_B2_P4 <- get_df_P4(df_B2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P4,varname))
  print("---------------------------------")
  print("B2_P8")
  df_B2_P8 <- get_df_P8(df_B2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P8,varname))
  sink(NULL)
}

FigS3_Comp_Type <- function(df,varname,outfile){
  sink(file=outfile)
  df_WT <- get_df_WT(df)
  print("---------------------------------")
  print("WT_P2")
  df_WT_P2 <- get_df_P2(df_WT)
  print_power_for_3pairs(get_Type_diff(df_WT_P2,varname))
  print("---------------------------------")
  print("WT_P4")
  df_WT_P4 <- get_df_P4(df_WT)
  print_power_for_3pairs(get_Type_diff(df_WT_P4,varname))
  print("---------------------------------")
  print("WT_P8")
  df_WT_P8 <- get_df_P8(df_WT)
  print_power_for_3pairs(get_Type_diff(df_WT_P8,varname))
  df_B2 <- get_df_B2(df)
  print("---------------------------------")
  print("B2_P2")
  df_B2_P2 <- get_df_P2(df_B2)
  print_power_for_3pairs(get_Type_diff(df_B2_P2,varname))
  print("---------------------------------")
  print("B2_P4")
  df_B2_P4 <- get_df_P4(df_B2)
  print_power_for_3pairs(get_Type_diff(df_B2_P4,varname))
  print("---------------------------------")
  print("B2_P8")
  df_B2_P8 <- get_df_P8(df_B2)
  print_power_for_3pairs(get_Type_diff(df_B2_P8,varname))
  sink(NULL)
}

Fig2_Comp_AZIndex <- function(df,varname,outfile){
  sink(file=outfile)
  df_WT <- get_df_WT(df)
  df_WT_P2 <- get_df_P2(df_WT)
  print("---------------------------------")
  print("WT_P2_AZ1")
  df_WT_P2_1 <- get_AZ_of(df_WT_P2,1)
  print_power_for_3pairs(get_CTB_diff(df_WT_P2_1,varname))
  print("---------------------------------")
  print("WT_P2_AZ2")
  df_WT_P2_2 <- get_AZ_of(df_WT_P2,2)
  print_power_for_3pairs(get_CTB_diff(df_WT_P2_2,varname))
  print("---------------------------------")
  print("WT_P2_AZ3")
  df_WT_P2_3 <- get_AZ_of(df_WT_P2,3)
  print_power_for_3pairs(get_CTB_diff(df_WT_P2_3,varname))
  print("---------------------------------")
  print("WT_P2_AZ4")
  df_WT_P2_4 <- get_AZ_of(df_WT_P2,4)
  print_power_for_3pairs(get_CTB_diff(df_WT_P2_4,varname))
  df_WT_P4 <- get_df_P4(df_WT)
  print("---------------------------------")
  print("WT_P4_AZ1")
  df_WT_P4_1 <- get_AZ_of(df_WT_P4,1)
  print_power_for_3pairs(get_CTB_diff(df_WT_P4_1,varname))
  print("---------------------------------")
  print("WT_P4_AZ2")
  df_WT_P4_2 <- get_AZ_of(df_WT_P4,2)
  print_power_for_3pairs(get_CTB_diff(df_WT_P4_2,varname))
  print("---------------------------------")
  print("WT_P4_AZ3")
  df_WT_P4_3 <- get_AZ_of(df_WT_P4,3)
  print_power_for_3pairs(get_CTB_diff(df_WT_P4_3,varname))
  print("---------------------------------")
  print("WT_P4_AZ4")
  df_WT_P4_4 <- get_AZ_of(df_WT_P4,4)
  print_power_for_3pairs(get_CTB_diff(df_WT_P4_4,varname))
  df_WT_P8 <- get_df_P8(df_WT)
  print("---------------------------------")
  print("WT_P8_AZ1")
  df_WT_P8_1 <- get_AZ_of(df_WT_P8,1)
  print_power_for_3pairs(get_CTB_diff(df_WT_P8_1,varname))
  print("---------------------------------")
  print("WT_P8_AZ2")
  df_WT_P8_2 <- get_AZ_of(df_WT_P8,2)
  print_power_for_3pairs(get_CTB_diff(df_WT_P8_2,varname))
  print("---------------------------------")
  print("WT_P8_AZ3")
  df_WT_P8_3 <- get_AZ_of(df_WT_P8,3)
  print_power_for_3pairs(get_CTB_diff(df_WT_P8_3,varname))
  print("---------------------------------")
  print("WT_P8_AZ4")
  df_WT_P8_4 <- get_AZ_of(df_WT_P8,4)
  print_power_for_3pairs(get_CTB_diff(df_WT_P8_4,varname))
  df_B2 <- get_df_B2(df)
  df_B2_P2 <- get_df_P2(df_B2)
  print("---------------------------------")
  print("B2_P2_AZ1")
  df_B2_P2_1 <- get_AZ_of(df_B2_P2,1)
  print_power_for_3pairs(get_CTB_diff(df_B2_P2_1,varname))
  print("---------------------------------")
  print("B2_P2_AZ2")
  df_B2_P2_2 <- get_AZ_of(df_B2_P2,2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P2_2,varname))
  print("---------------------------------")
  print("B2_P2_AZ3")
  df_B2_P2_3 <- get_AZ_of(df_B2_P2,3)
  print_power_for_3pairs(get_CTB_diff(df_B2_P2_3,varname))
  print("---------------------------------")
  print("B2_P2_AZ4")
  df_B2_P2_4 <- get_AZ_of(df_B2_P2,4)
  print_power_for_3pairs(get_CTB_diff(df_B2_P2_4,varname))
  df_B2_P4 <- get_df_P4(df_B2)
  print("---------------------------------")
  print("B2_P4_AZ1")
  df_B2_P4_1 <- get_AZ_of(df_B2_P4,1)
  print_power_for_3pairs(get_CTB_diff(df_B2_P4_1,varname))
  print("---------------------------------")
  print("B2_P4_AZ2")
  df_B2_P4_2 <- get_AZ_of(df_B2_P4,2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P4_2,varname))
  print("---------------------------------")
  print("B2_P4_AZ3")
  df_B2_P4_3 <- get_AZ_of(df_B2_P4,3)
  print_power_for_3pairs(get_CTB_diff(df_B2_P4_3,varname))
  print("---------------------------------")
  print("B2_P4_AZ4")
  df_B2_P4_4 <- get_AZ_of(df_B2_P4,4)
  print_power_for_3pairs(get_CTB_diff(df_B2_P4_4,varname))
  df_B2_P8 <- get_df_P8(df_B2)
  print("---------------------------------")
  print("B2_P8_AZ1")
  df_B2_P8_1 <- get_AZ_of(df_B2_P8,1)
  print_power_for_3pairs(get_CTB_diff(df_B2_P8_1,varname))
  print("---------------------------------")
  print("B2_P8_AZ2")
  df_B2_P8_2 <- get_AZ_of(df_B2_P8,2)
  print_power_for_3pairs(get_CTB_diff(df_B2_P8_2,varname))
  print("---------------------------------")
  print("B2_P8_AZ3")
  df_B2_P8_3 <- get_AZ_of(df_B2_P8,3)
  print_power_for_3pairs(get_CTB_diff(df_B2_P8_3,varname))
  print("---------------------------------")
  print("B2_P8_AZ4")
  df_B2_P8_4 <- get_AZ_of(df_B2_P8,4)
  print_power_for_3pairs(get_CTB_diff(df_B2_P8_4,varname))
  sink(NULL)
}